[general]
dotenv_filename = "/home/domotik/.config/domotik/automations.env"

[mqtt]
hostname = "localhost"
port = 1883

[domotik]
hostname = "localhost"
port = 8100

[smtp]
hostname = "smtp.gmail.com"
port = 587

[logger]
aiohttp = "WARNING"

[logger.automations]
automations = "INFO"

[postgresql]
hostname = "localhost"
port = 5432
username = "domotik"
databasename = "domotiq"

[periodicity]
pressure = 600
linky = 60
